{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lobehub.fullname" . }}
  labels:
    {{- include "lobehub.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.auth.authSecret }}
  AUTH_SECRET: {{ .Values.auth.authSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.accessCode }}
  ACCESS_CODE: {{ .Values.auth.accessCode | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.keyVaultsSecret }}
  KEY_VAULTS_SECRET: {{ .Values.auth.keyVaultsSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.database.url }}
  DATABASE_URL: {{ .Values.database.url | b64enc | quote }}
  {{- end }}
  {{- if .Values.redis.url }}
  REDIS_URL: {{ .Values.redis.url | b64enc | quote }}
  {{- end }}
  {{- if .Values.s3.accessKeyId }}
  S3_ACCESS_KEY_ID: {{ .Values.s3.accessKeyId | b64enc | quote }}
  {{- end }}
  {{- if .Values.s3.secretAccessKey }}
  S3_SECRET_ACCESS_KEY: {{ .Values.s3.secretAccessKey | b64enc | quote }}
  {{- end }}
{{- end }}
