apiVersion: v1
kind: Service
metadata:
  name: {{ include "subconverter.fullname" . }}
  labels:
    {{- include "subconverter.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
  {{- if .Values.frontend.enabled }}
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  {{- end }}
  - name: backend
    port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
  selector:
    {{- include "subconverter.selectorLabels" . | nindent 4 }}
