{{- if .Values.mysql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "axonhub.mysql.serviceName" . }}
  labels:
    {{- include "axonhub.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "axonhub.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
{{- end }}
