{{- include "deeplx.validate" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deeplx.fullname" . }}
  namespace: {{ include "deeplx.namespace" . | quote }}
  labels:
    {{- include "deeplx.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: {{ .Values.updateStrategy.type }}
    {{- if eq .Values.updateStrategy.type "RollingUpdate" }}
    rollingUpdate:
      {{- include "common.tplvalues.render" (dict "value" .Values.updateStrategy.rollingUpdate "context" $) | nindent 6 }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "deeplx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "deeplx.podLabels" . | nindent 8 }}
      {{- if or .Values.podAnnotations .Values.commonAnnotations }}
      annotations:
        {{- include "common.tplvalues.merge" (dict "values" (list .Values.podAnnotations .Values.commonAnnotations) "context" $) | nindent 8 }}
        {{- if and (not .Values.auth.existingSecret.name) (or .Values.auth.token .Values.auth.dlSession .Values.auth.proxy) }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
      {{- else if and (not .Values.auth.existingSecret.name) (or .Values.auth.token .Values.auth.dlSession .Values.auth.proxy) }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- end }}
    spec:
      {{- include "common.images.renderPullSecrets" (dict "images" (list .Values.image) "context" $) | nindent 6 }}
      serviceAccountName: {{ include "deeplx.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext:
        {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- with .Values.schedulerName }}
      schedulerName: {{ . | quote }}
      {{- end }}
      containers:
        - name: deeplx
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext:
            {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          image: {{ include "common.images.image" (dict "imageRoot" .Values.image "global" .Values.global) | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 1188
              protocol: TCP
          env:
            - name: IP
              value: 0.0.0.0
            - name: PORT
              value: "1188"
            {{- if include "deeplx.authEnabled" . }}
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "deeplx.secretName" . }}
                  optional: true
                  key: {{ include "common.secrets.key" (dict "existingSecret" .Values.auth.existingSecret "key" "token") }}
            - name: DL_SESSION
              valueFrom:
                secretKeyRef:
                  name: {{ include "deeplx.secretName" . }}
                  optional: true
                  key: {{ include "common.secrets.key" (dict "existingSecret" .Values.auth.existingSecret "key" "dlSession") }}
            - name: PROXY
              valueFrom:
                secretKeyRef:
                  name: {{ include "deeplx.secretName" . }}
                  optional: true
                  key: {{ include "common.secrets.key" (dict "existingSecret" .Values.auth.existingSecret "key" "proxy") }}
            {{- end }}
            {{- with .Values.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 12 }}
            {{- end }}
          {{- if or .Values.extraEnvVarsCM .Values.extraEnvVarsSecret }}
          envFrom:
            {{- with .Values.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" . "context" $) }}
            {{- end }}
            {{- with .Values.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" . "context" $) }}
            {{- end }}
          {{- end }}
          {{- if .Values.customReadinessProbe }}
          readinessProbe:
            {{- include "common.tplvalues.render" (dict "value" .Values.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if .Values.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: http
            {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.customLivenessProbe }}
          livenessProbe:
            {{- include "common.tplvalues.render" (dict "value" .Values.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if .Values.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: http
            {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- include "common.tplvalues.render" (dict "value" .Values.resources "context" $) | nindent 12 }}
          {{- with .Values.extraVolumeMounts }}
          volumeMounts:
            {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 12 }}
          {{- end }}
      {{- with .Values.extraVolumes }}
      volumes:
        {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- include "common.tplvalues.render" (dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- else if or .Values.podAffinityPreset .Values.podAntiAffinityPreset .Values.nodeAffinityPreset.type }}
      affinity:
        {{- include "deeplx.presetAffinity" . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}
      {{- end }}
