{{- if and (not .Values.auth.existingSecret.name) (or .Values.auth.token .Values.auth.dlSession .Values.auth.proxy) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deeplx.secretName" . }}
  namespace: {{ include "deeplx.namespace" . | quote }}
  labels:
    {{- include "deeplx.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- with .Values.auth.token }}
  TOKEN: {{ . | quote }}
  {{- end }}
  {{- with .Values.auth.dlSession }}
  DL_SESSION: {{ . | quote }}
  {{- end }}
  {{- with .Values.auth.proxy }}
  PROXY: {{ . | quote }}
  {{- end }}
{{- end }}
