apiVersion: v2
name: tracing-stack
description: Kubernetes and application observability with Grafana, Prometheus Operator,
  Loki, Tempo and OpenTelemetry
type: application
version: 1.1.0-alpha.0
kubeVersion: '>=1.25.0-0'
dependencies:
- name: homelab-common
  version: 0.1.0
  repository: file://../homelab-common
- name: grafana
  version: 12.3.0
  repository: https://grafana-community.github.io/helm-charts
  condition: global.grafana.install
- name: kube-prometheus-stack
  version: 84.4.0
  repository: https://prometheus-community.github.io/helm-charts
  condition: global.prometheus.install
  alias: monitoring
- name: tempo
  version: 1.24.4
  repository: https://grafana.github.io/helm-charts
- name: opentelemetry-collector
  alias: gateway
  version: 0.145.0
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
- name: loki
  version: 6.53.0
  repository: https://grafana.github.io/helm-charts
  condition: global.loki.install
- name: alloy
  version: 1.10.1
  repository: https://grafana.github.io/helm-charts
  condition: alloy.enabled
- name: opentelemetry-collector
  alias: otlp-edge
  version: 0.145.0
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  condition: otlp-edge.enabled
