{{- if and .Values.persistence.books.enabled (not .Values.persistence.books.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "booklore.fullname" . }}-books
  labels:
    {{- include "booklore.labels" . | nindent 4 }}
  {{- with .Values.persistence.books.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.books.accessModes | nindent 4 }}
  {{- if .Values.persistence.books.storageClass }}
  storageClassName: {{ .Values.persistence.books.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.books.size }}
{{- end }}
