{{- if and (not .Values.mariadb.enabled) .Values.externalDatabase.host (not .Values.externalDatabase.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "booklore.externalDatabase.secretName" . }}
  labels:
    {{- include "booklore.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.externalDatabase.password | quote }}
{{- end }}
